### ISSUE TITLE
Regression: Jacksum 3.0.0 to 3.4.0 hangs while trying to read NTUSER.DAT on Microsoft Windows if more than one algo has been selected

### ISSUE THREAD

**Issue by jonelo** [jonelo/jacksum#24]
**Describe the bug**
Jacksum 3.0.0 to 3.4.0 hangs while trying to read NTUSER.DAT on Microsoft Windows.
Issue occurs in concurrency mode only, i. e. if more than one algo has been selected.

**To Reproduce**
```
C:\Users\Johann>jacksum34 -a md5+sha256 -V all -r 1 .
...
.\NTUSER.DAT (Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)
java.io.FileNotFoundException: .\NTUSER.DAT (Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at net.jacksum.multicore.manyalgos.DataReader.run(DataReader.java:78)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
process hangs.

**Expected behavior**
it should not hang, but print out the error only and continue.
```
Jacksum: Error: .\NTUSER.DAT (Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)
```

**Screenshots**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by jonelo** [comment]
**Workaround:**
```
C:\Users\Johann>java -Djacksum.concurrency.manyalgos=false -jar \Applications\jacksum-3.4.0\jacksum-3.4.0.jar -a md5+sha256 -V all -r 1 .
```

**Comment by jonelo** [comment]
fixed.
